Friends list component
varangill/Synker pull request #9
Opened 2024-08-15 00:11 UTC by 3ricLu

- UI Changes
- Friend List component now displays friends and group chats

2024-08-18 05:03 UTC, varangill requested changes
Few minor changes to make but otherwise it's good

2024-08-18 05:03 UTC, varangill commented on client/src/ui/components/friends/FriendsList.tsx
> +  const [addFriend, setAddFriend] = useState("");
`addFriend` sounds odd, name should probably better describe what it is, like `addFriendInput`

2024-08-18 05:03 UTC, varangill commented on client/src/ui/components/friends/FriendsList.tsx
> +  chatItems: ChatList[];
Is this `FriendsList` component also containing group chats? if so, the folder `friends` and this file should probably be renamed to be more accurate since there's a distinction between `friends` and `chats`

2024-08-18 05:03 UTC, varangill commented on client/src/ui/components/friends/FriendsList.tsx
> +  const addFriendClick = (addFriend: string) => {
would rename this (and other similar `onClick` functions in the future) to something like `onClickAddFriend` just to make it a bit more clear it's an on click handler

2024-08-18 05:03 UTC, varangill commented on client/src/ui/utils/ShowToast.tsx
> +export const showToast = (message: string, type: "success" | "error") => {
Probably cleaner to just make two `showSuccessToast` and a `showErrorToast` functions instead? i don't think this would need to be dynamic at least

2024-08-18 08:25 UTC, 3ricLu commented on client/src/ui/components/friends/FriendsList.tsx
> +  chatItems: ChatList[];
Renamed chatlist and component to conversation and conversationlist as it includes both direct messages from friends and group chats. 

Messages themselves are pulled separately when the user clicks on a conversation and will be rendered in a separate unfinished component.

2024-08-19 02:02 UTC, varangill approved these changes

2024-08-19 02:04 UTC, merged